#!/bin/sh

# Ensure we are being ran as root
if [ $(id -u) -ne 0 ]; then
	echo "This script must be ran as root"
	exit 1
fi

clear
echo " |--------------------------------| "
echo " | Installing AhMyth Prerequisits | "
echo " |--------------------------------| "
sleep 2

apt-get install xterm -y # Used for the Repo_Swap in order to install older packages from older software repostiories without having to 
# add the repository mirrors to your sources.list file
# see more information on the Repo_Swap here at https://github.com/Morsmalleo/SoftwareRepo_Automation
apt-get install npm nodejs -y
clear
sleep 1

clear
echo " AhMyth now supports Java 11 Development Kit, but it is still recommended "
echo " to install Java 8 Development Kit in case of errors simply because "
echo " Java 11 support for AhMyth is still in beta phases "
sleep 15
clear

echo " Do you want to install Java 8 Development Kit for AhMyth? "
echo "$cyan" "Choose y/n : "
read -r cho
case "$cho" in

y|Y|Yes|yes|YES)
# Creates an Ahmyth.list file inside the 'sources.list.d' folder for the installation of openjdk-8-jdk via the Repo_Swap
touch /etc/apt/sources.list.d/Ahmyth.list
echo "deb http://deb.debian.org/debian stretch main contrib non-free" > /etc/apt/sources.list.d/Ahmyth.list
xterm -T " Updating Repositories Debian Stretch " -geometry 100x30 -e "apt-get clean && apt-get clean cache && apt-get update -y"
sleep 2

apt-get install -y openjdk-8-jdk* openjdk-8-jre*

clear
echo " |---------------------------------------------| "
echo " | Removing Debian Stretch software repository | "
echo " |---------------------------------------------| "
rm -f /etc/apt/sources.list.d/Ahmyth.list
clear
# Now we can reactivate original software repositories without the stretch software repo interfering
xterm -T " Updating Your Original/Current Repositories " -geometry 100x30 -e "apt-get update"
clear
sleep 2
clear
echo " |------------------------------------------------------------------------------| "
echo " | Installation completed, Java 8 Development Kit for AhMyth has been installed | "
echo " |------------------------------------------------------------------------------| "
;;

n|no|No|NO)
clear
echo " |-------------------------------------------------------------| "
echo " | Ok, we will install Java 11 Development Kit for you instead | "
echo " |-------------------------------------------------------------| "
sleep 4

clear
echo " |------------------------------------| "
echo " | Installing Java 11 Development Kit | "
echo " |------------------------------------| "

apt-get install openjdk-11-jdk* openjdk-11-jre*
esac

clear
echo " |--------------------------------------------| "
echo " | Java 11 Development Kit has been installed | "
echo " |--------------------------------------------| "
sleep 2

echo " |-------------------| "
echo " | Installing AhMyth | "
echo " |-------------------| " 
su -c "npm install && npm audit fix" kali
clear
/usr/bin/update-alternatives --config java
dir=`pwd`
scrp="cd $dir && npm start"
rm -f /usr/local/sbin/ahmyth
touch /usr/local/sbin/ahmyth
echo "#!/bin/bash" > /usr/local/sbin/ahmyth
echo "$scrp" >> /usr/local/sbin/ahmyth
cd .. && cp "Config/AhMyth.desktop" /usr/share/applications/AhMyth.desktop
cp "AhMyth-Server/build/icons-inverted/64x64.png" /usr/share/icons/64x64.png
chmod +x /usr/local/sbin/ahmyth

clear
echo " |------------------------------------------------------------------------------------| "
echo " | Installation completed, To execute AhMyth, type 'ahmyth' anywhere in your terminal | "
echo " |------------------------------------------------------------------------------------| "
sleep 5
echo " |-----------------------------------------------------------------| "
echo " | or type 'npm start' inside the 'AhMyth/AhMyth-Server' directory | "
echo " |-----------------------------------------------------------------| "
clear
exit 0
fi
;; 
