#!/bin/sh

# Ensure we are being ran as root
if [ $(id -u) -ne 0 ]; then
	echo "This script must be run as root"
	exit 1
fi

clear
echo " |--------------------------------| "
echo " | Installing AhMyth Prerequisits | "
echo " |--------------------------------| "
sleep 2

# xterm is needed for the Repo_Swap in order to install
# Java 8 development kit from an older software Repo
# without having to manually add it to your sources.list
apt-get install xterm -y 
apt-get install npm nodejs -y
apt-get install aapt android-framework-res -y
clear
sleep 1

echo " |--------------------------------------------------------------------------| "
echo " | Do you want to install Java 8 openjdk or Java 11 openjdk for AhMyth?     | "
echo " | or choose 'Skip' if you already have one or both java versions installed | "
echo " |--------------------------------------------------------------------------| " 
echo "$cyan" "Choose 11/8/Skip : "
read -r cho
case "$cho" in

8|eight)
# Creates an Ahmyth.list file inside the 'sources.list.d' 
# folder for the Repo_Swap, more info on the Repo_Swap
# here - https://github.com/Morsmalleo/Repo_Swap
touch /etc/apt/sources.list.d/Ahmyth.list
echo "deb http://deb.debian.org/debian stretch main contrib non-free" > /etc/apt/sources.list.d/Ahmyth.list
xterm -T " Updating Repositories Debian Stretch " -geometry 100x30 -e "apt-get clean && apt-get clean cache && apt-get update -y"
sleep 2

# the '/stretch' argument allows the script to target jdk-8 from the stretch repo only, 
# this is to prevent installing other versions from parrot repo's along with stretch's version, 
# as this will cause java installation breakage, using the '/stretch' argument allows the script 
# to work safely on both Parrot OS and Kali Linux with out the need to # out any of the Kali or Parrot
# software repositories
apt-get install -y openjdk-8-jdk*/stretch openjdk-8-jre*/stretch

clear
echo " |---------------------------------------------| "
echo " | Removing Debian Stretch software repository | "
echo " |---------------------------------------------| "
sleep 5
# Removes Ahmyth.list file in 'etc/apt/sources.list.d'
rm -f /etc/apt/sources.list.d/Ahmyth.list
clear
# Now we can reactivate original software repositories without the stretch software repo interfering
xterm -T " Updating Your Original/Current Repositories " -geometry 100x30 -e "apt-get update"
clear
sleep 2
clear
echo " |-------------------------------------------| "
echo " | Java 8 Development Kit has been installed | "
echo " |-------------------------------------------| "
sleep 4
clear
echo " |-------------------| "
echo " | Installing AhMyth | "
echo " |-------------------| " 
sleep 2
# Install's electron globally, so you can operate ahmyth without needing to run 'npm install', works for both Kali and Parrot FINALLY!
sh -c "sudo npm install -g electron@9.4.1"
sleep 5
clear
/usr/bin/update-alternatives --config java
# Creates the 'ahmyth' system shortcut file 
dir=`pwd`
scrp="cd $dir && npm start"
rm -f /usr/local/sbin/ahmyth
touch /usr/local/sbin/ahmyth
echo "#!/bin/bash" > /usr/local/sbin/ahmyth
echo "$scrp" >> /usr/local/sbin/ahmyth
cd .. && cp "Config/AhMyth.desktop" /usr/share/applications/AhMyth.desktop
cp "AhMyth-Server/build/icons-inverted/64x64.png" /usr/share/icons/64x64.png
chmod +x /usr/local/sbin/ahmyth

clear
echo " |------------------------------------------------------------------------------------| "
echo " | Installation completed, To execute AhMyth, type 'ahmyth' anywhere in your terminal | "
echo " |------------------------------------------------------------------------------------| "
sleep 5
echo " |-----------------------------------------------------------------| "
echo " | or type 'npm start' inside the 'AhMyth/AhMyth-Server' directory | "
echo " |-----------------------------------------------------------------| "
sleep 5
clear
exit 0 
;;

11|eleven)
clear
echo " |-----------------------------------------------------| "
echo " | Ok, we will install Java 11 Development Kit for you | "
echo " |-----------------------------------------------------| "
sleep 4

clear
echo " |------------------------------------| "
echo " | Installing Java 11 Development Kit | "
echo " |------------------------------------| "

apt-get install openjdk-11-jdk* openjdk-11-jre* -y

clear
echo " |--------------------------------------------| "
echo " | Java 11 Development Kit has been installed | "
echo " |--------------------------------------------| "
sleep 2
clear
echo " |-------------------| "
echo " | Installing AhMyth | "
echo " |-------------------| " 
sleep 2
# Install's electron globally, so you can operate ahmyth without needing to run 'npm install', works for both Kali and Parrot FINALLY!
sh -c "sudo npm install -g electron@9.4.1"
sleep 5
clear
/usr/bin/update-alternatives --config java
# Creates the 'ahmyth' system shortcut file 
dir=`pwd`
scrp="cd $dir && npm start"
rm -f /usr/local/sbin/ahmyth
touch /usr/local/sbin/ahmyth
echo "#!/bin/bash" > /usr/local/sbin/ahmyth
echo "$scrp" >> /usr/local/sbin/ahmyth
cd .. && cp "Config/AhMyth.desktop" /usr/share/applications/AhMyth.desktop
cp "AhMyth-Server/build/icons-inverted/64x64.png" /usr/share/icons/64x64.png
chmod +x /usr/local/sbin/ahmyth

clear
echo " |------------------------------------------------------------------------------------| "
echo " | Installation completed, To execute AhMyth, type 'ahmyth' anywhere in your terminal | "
echo " |------------------------------------------------------------------------------------| "
sleep 5
echo " |-----------------------------------------------------------------| "
echo " | or type 'npm start' inside the 'AhMyth/AhMyth-Server' directory | "
echo " |-----------------------------------------------------------------| "
sleep 5
clear
exit 0 
;;

Skip|S|skip|s)
clear
echo " |-------------------| "
echo " | Installing AhMyth | "
echo " |-------------------| " 
sleep 2
# Install's electron globally, so you can operate ahmyth without needing to run 'npm install', works for both Kali and Parrot FINALLY!
sh -c "sudo npm install -g electron@9.4.1"
sleep 5
clear
/usr/bin/update-alternatives --config java
# Creates the 'ahmyth' system shortcut file 
dir=`pwd`
scrp="cd $dir && npm start"
rm -f /usr/local/sbin/ahmyth
touch /usr/local/sbin/ahmyth
echo "#!/bin/bash" > /usr/local/sbin/ahmyth
echo "$scrp" >> /usr/local/sbin/ahmyth
cd .. && cp "Config/AhMyth.desktop" /usr/share/applications/AhMyth.desktop
cp "AhMyth-Server/build/icons-inverted/64x64.png" /usr/share/icons/64x64.png
chmod +x /usr/local/sbin/ahmyth

clear
echo " |------------------------------------------------------------------------------------| "
echo " | Installation completed, To execute AhMyth, type 'ahmyth' anywhere in your terminal | "
echo " |------------------------------------------------------------------------------------| "
sleep 5
echo " |-----------------------------------------------------------------| "
echo " | or type 'npm start' inside the 'AhMyth/AhMyth-Server' directory | "
echo " |-----------------------------------------------------------------| "
sleep 5
clear
esac
exit 0
fi 
