#!/bin/bash

# Ensure we are being ran as root
if [ $(id -u) -ne 0 ]; then
	echo "This script must be ran as root"
	exit 1
fi

clear
echo " AhMyth now supports Java 11 Development Kit, but it is still recommended "
echo " to install Java 8 Development Kit in case of errors simply because "
echo " Java 11 support for AhMyth is still in beta phases "
sleep 10
clear

echo "Do you want to install Java 8 Development Kit for AhMyth?"
echo "$cyan" "Choose y/n : "
read -r cho
case "$cho" in

y|Y|Yes|yes|YES)
# Creates an Ahmyth.list file inside the sources.list.d folder for the installation of openjdk-8-jdk from the Debian Stretch software repo
touch /etc/apt/sources.list.d/Ahmyth.list
echo "deb http://deb.debian.org/debian stretch main contrib non-free" > /etc/apt/sources.list.d/Ahmyth.list
xterm -T " Updating Repositories Debian Stretch " -geometry 100x30 -e "apt-get clean && apt-get clean cache && apt-get update -y"
sleep 2

apt-get install -y openjdk-8-jdk* openjdk-8-jre*

clear
echo " |---------------------------------------------| "
echo " | Removing Debian Stretch software repository | "
echo " |---------------------------------------------| "
rm -f /etc/apt/sources.list.d/Ahmyth.list
# Now we can reactivate original software repositories without the stretch software repo interfering
xterm -T " Updating Your Original/Current Repositories " -geometry 100x30 -e "apt-get update"
clear
sleep 2
clear
echo " |------------------------------------------------------------------------------| "
echo " | Installation completed, Java 8 Development Kit for AhMyth has been installed | "
echo " |------------------------------------------------------------------------------| "
;;

n|no|No|NO)
clear
echo " |-------------------------------------------------------------| "
echo " | Ok, we will install Java 11 Development Kit for you instead | "
echo " |-------------------------------------------------------------| "
sleep 4

clear
echo " |------------------------------------| "
echo " | Installing Java 11 Development Kit | "
echo " |------------------------------------| "

apt-get install openjdk-11-jdk* openjdk-11-jre*
esac 