name: Client Report - Standalone
description: Report an issue with a deployed Standalone AhMyth Client/Payload.
title: 'client report: '
labels: ['client error']
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <picture>
            <source
              width="356px"
              media="(prefers-color-scheme: dark)"
              srcset="https://raw.githubusercontent.com/Morsmalleo/AhMyth/master/.github/IMG/Circle-Logo.png"
            >
            <img 
              width="356px"
              src="https://raw.githubusercontent.com/Morsmalleo/AhMyth/master/.github/IMG/Circle-Logo.png"
            >
          </picture>
           <br>
           Continuing the legacy of the AhMyth R.A.T Project
        </p>

        # AhMyth Client Report

        Before creating a new standalone client report, please keep the following in mind:
        - **Do not use this to report problems with deployed bound clients/payloads, only use this report for problems with deployed standalone clients/payloads**
        - **Do not submit a duplicate standalone client reports**: You can review existing standalone client reports [here](https://github.com/Morsmalleo/AhMyth/labels/client%20Error) & [here](https://github.com/Morsmalleo/AhMyth/labels/Client%20Bug).
        - **Review the Issue Rules**: Make sure your standalone client report adheres to these rules. You can find the guidelines [here](https://github.com/Morsmalleo/AhMyth/#Issue-Rules).
  - type: textarea
    attributes:
      label: Standalone Client Issue Description
      description: |
        - Describe your standalone client issue in detail
        - Add steps to reproduce the standalone client issue if possible (Step 1. ... Step 2. ...)
        - Add images and videos if possible
    validations:
        required: true
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution to the standalone client issue. Otherwise just mark this section as "N/a"
  - type: textarea
    attributes:
      label: Additional context
      description: If applicable, add additional context here.
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your standalone client report will be closed if you don't follow the checklist below.
      options:
        - label: This issue is not a duplicate of an existing standalone client report.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
