name: client report
description: Report an issue with the AhMyth Client.
title: 'client report: '
labels: ['client error']
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <picture>
            <source
              width="356px"
              media="(prefers-color-scheme: dark)"
              srcset="https://raw.githubusercontent.com/Morsmalleo/AhMyth/Development/.github/IMG/Circle-Logo.png"
            >
            <img 
              width="356px"
              src="https://raw.githubusercontent.com/Morsmalleo/AhMyth/Development/.github/IMG/Circle-Logo.png"
            >
          </picture>
           <br>
           Continuing the legacy of the AhMyth R.A.T Project
        </p>

        # AhMyth Client Report

        Before creating a new client report, please keep the following in mind:
        - **Do not use this report for bound clients/payloads, only use this report for standalone clients/payloads**
        - **Do not submit a duplicate client report**: You can review existing client reports [here](https://github.com/Morsmalleo/AhMyth/labels/client%20Error).
        - **Review the Issue Rules**: Make sure your client report adheres to these rules. You can find the guidelines [here](https://github.com/Morsmalleo/AhMyth/#Issue-Rules).
  - type: textarea
    attributes:
      label: client issue description
      description: |
        - Describe your client issue in detail
        - Add steps to reproduce the client issue if possible (Step 1. ... Step 2. ...)
        - Add images and videos if possible
    validations:
        required: true
  - type: textarea
    attributes:
      label: Error logs
      description: If applicable, please post the error logs that are generated `C:\yourUserName\AhMyth\Logs | /home/youUserName/AhMyth/Logs`.
      render: shell
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution to the client issue.
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your client report will be closed if you don't follow the checklist below.
      options:
        - label: This issue is not a duplicate of an existing client report.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
