name: Client Report - Bound
description: Report an issue with a deployed bound AhMyth Client.
title: 'binding report: '
labels: ['binding error']
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <picture>
            <source
              width="356px"
              media="(prefers-color-scheme: dark)"
              srcset="https://raw.githubusercontent.com/Morsmalleo/AhMyth/master/.github/IMG/Circle-Logo.png"
            >
            <img 
              width="356px"
              src="https://raw.githubusercontent.com/Morsmalleo/AhMyth/master/.github/IMG/Circle-Logo.png"
            >
          </picture>
           <br>
           Continuing the legacy of the AhMyth R.A.T Project
        </p>

        # AhMyth Binding Report

        Before creating a new bound client report, please keep the following in mind:

        - **Do not use this report for errors that arise during the Binding Processes, only use this report for bound clients/payloads that have been deployed**
        - **Do not use this report for standalone clients/payloads, only use this report for bound clients/payloads that have been deployed**
        - **Do not submit a duplicate bound client report**: You can review existing bound client reports [here](https://github.com/Morsmalleo/AhMyth/labels/binding).
        - **Review the Issue Rules**: Make sure your bound client report adheres to these rules. You can find the guidelines [here](https://github.com/Morsmalleo/AhMyth/#Issue-Rules).
  - type: checkboxes
    id: payloadOptions
    attributes:
      label: Payload Options
      options:
        - label: Activity-method bound payload
        - label: Boot-method bound payload
    validations:
      required: true
  - type: textarea
    attributes:
      label: binding issue description 
      description: |
        - Describe your issue with your bound client in detail
        - Add steps to reproduce the issue with the bound client if possible (Step 1. ... Step 2. ...)
        - Add images and videos if possible
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution to the bound client issue. Otherwise just mark this as "N/A"
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your bound client report will be closed if you don't follow the checklist below.
      options:
        - label: This issue is not a duplicate of an existing bound client report.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
