name: Server report
description: Report an issue with the AhMyth Server.
title: 'server report: '
labels: ['server error', 'server bug']
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <picture>
            <source
              width="356px"
              media="(prefers-color-scheme: dark)"
              srcset="https://raw.githubusercontent.com/Morsmalleo/AhMyth/master/.github/IMG/Circle-Logo.png"
            >
            <img 
              width="356px"
              src="https://raw.githubusercontent.com/Morsmalleo/AhMyth/master/.github/IMG/Circle-Logo.png"
            >
          </picture>
           <br>
           Continuing the legacy of the AhMyth R.A.T Project
        </p>

        # AhMyth Server Report

        Before creating a new server report, please keep the following in mind:

        - **Do not submit a duplicate server report**: You can review existing server reports [here](https://github.com/Morsmalleo/AhMyth/labels/Server%20Error) & [here](https://github.com/Morsmalleo/AhMyth/labels/Server%20Bug).
        - **Review the Issue Rules**: Make sure your server report adheres to these rules. You can find the guidelines [here](https://github.com/Morsmalleo/AhMyth/#Issue-Rules).
  - type: textarea
    attributes:
      label: server issue description
      description: |
        - Describe your server issue in detail
        - Add steps to reproduce the server issue if possible (Step 1. ... Step 2. ...)
        - Add images and videos if possible
    validations:
        required: true
  - type: textarea
    attributes:
      label: Error logs
      description: Please post the error logs that are generated `C:\yourUserName\AhMyth\Logs | /home/youUserName/AhMyth/Logs`.
      render: shell
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution to the server issue.
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your server report will be closed if you don't follow the checklist below.
      options:
        - label: This issue is not a duplicate of an existing server report.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
