apply plugin: 'com.android.application'

android {
    compileSdkVersion 34
    buildToolsVersion '34.0.0'
    defaultConfig {
        applicationId "ahmyth.mine.king.ahmyth"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        lintOptions {
            abortOnError false
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dependencies {
        // AndroidX Support Libraries (instead of com.android.support)
        implementation 'androidx.appcompat:appcompat:1.6.1' // Replace support-compat
        implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
        implementation fileTree(dir: 'libs', include: ['*.jar'])
        
        // Testing dependencies (AndroidX Test)
        androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
        androidTestImplementation 'androidx.test.ext:junit:1.1.5'

        // Socket.io client library
        implementation('io.socket:socket.io-client:0.8.3') {
            // excluding org.json which is provided by Android
            exclude group: 'org.json', module: 'json'
        }

        // Unit testing dependency
        testImplementation 'junit:junit:4.13.2'
    }
}
